spring:
  application:
    name: student #该值用来作为InquiryBankController具体实现类Controller的@RequestMapping前缀，不同接入行配置不同的applicationName
  datasource:
    name: student
    url: jdbc:mysql://10.10.13.7:3306/account_dispatcher?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: devuser
    password: devuser
    initialize: true
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
server:
  port: 9002